#
# This is a *fake / non-functional* travis configuration file.
#
# Its sole purpose at the moment is to record which Cartopy version was
# used for testing.
#
# Cartopy version: 3ba61c91f3c291918355a7870b4a485222b85375
#


language: Spree

python:
  # this is not actually used. Because it would take an overly long time
  # to build scipy we cannot use the virtual env of travis. Instead, we use the
  # standard apt-get installation of python2.7. See
  # https://groups.google.com/forum/#!msg/travis-ci/uJgu35XKdmI/UA0Kj1EhavAJ
  # for the discussion topic
  #
  - 2.7

install:
  - ./.travis_no_output sudo apt-get install python-scipy python-pip cython
  #- ./.travis_no_output sudo /usr/bin/pip install https://github.com/downloads/matplotlib/matplotlib/matplotlib-1.2.0rc3.tar.gz
  # http://www.webupd8.org/2010/10/fix-nopubkey-error-for-extras-ubuntu.html
  - ./.travis_no_output sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 3E5C1192
  - yes | ./.travis_no_output sudo add-apt-repository ppa:olivier-berten/geo
  - ./.travis_no_output sudo apt-get update
  - ./.travis_no_output sudo apt-get install libgeos-dev libproj-dev
  - ./.travis_no_output sudo /usr/bin/pip install --use-mirrors shapely pyshp pyke

  - ./.travis_no_output sudo apt-get install libnetcdf-dev netcdf-bin libhdf5-dev
  - ./.travis_no_output sudo /usr/bin/pip install netCDF4

  - ./.travis_no_output git clone https://github.com/SciTools/cartopy.git
  - cd cartopy
  - ./.travis_no_output /usr/bin/python setup.py install --user
  - cd ..
  
  # make udunits
  - mkdir udunits_src
  - cd udunits_src
  - wget ftp://ftp.unidata.ucar.edu/pub/udunits/udunits-2.1.24.tar.gz
  - tar xzf udunits-2.1.24.tar.gz
  - cd udunits-2.1.24
  - ./configure
  - make
  - make install


  # install iris in the .local directory (in lieu of using virtual env...)
  - ./.travis_no_output /usr/bin/python setup.py install --user

script:
  - mkdir ../test_folder
  - cd ../test_folder
  - /usr/bin/python -m unittest discover -v -s iris.tests
