#
# Based on pelson's travis work for cartopy.
#
# Please update the cartopy checksum below as appropriate.
#
# Note: Contrary to the travis documentation,
# http://about.travis-ci.org/docs/user/languages/python/#Travis-CI-Uses-Isolated-virtualenvs
# we will use the system python because it takes too long to install scipy from source.
#


language: python
python:
  - 2.7

install:

# add repo
  - ./.travis_no_output sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 3E5C1192
  - yes | ./.travis_no_output sudo add-apt-repository ppa:olivier-berten/geo
  - ./.travis_no_output sudo apt-get update

# install deps
  - ./.travis_no_output sudo apt-get install python-scipy cython python-pip
  - ./.travis_no_output sudo /usr/bin/pip install --use-mirrors shapely nose pyshp pep8 mock
  - ./.travis_no_output sudo /usr/bin/pip install matplotlib
  - ./.travis_no_output sudo apt-get install libgeos-dev libproj-dev
  - ./.travis_no_output sudo apt-get install libudunits2-dev libhdf5-serial-dev netcdf-bin libnetcdf-dev
  - ./.travis_no_output sudo apt-get install make unzip python-sphinx
  - ./.travis_no_output sudo /usr/bin/pip install pyke netCDF4
  - ./.travis_no_output sudo apt-get install python-gdal

# grib api
  - ./.travis_no_output sudo apt-get install libjasper-dev
  - ./.travis_no_output sudo apt-get build-dep libgrib-api-1.9.9 libgrib-api-dev libgrib-api-tools
  - ./.travis_no_output wget https://software.ecmwf.int/wiki/download/attachments/3473437/grib_api-1.9.16.tar.gz --no-check-certificate
  - ./.travis_no_output tar -xvf grib_api-1.9.16.tar.gz
  - cd grib_api-1.9.16/
  - ../.travis_no_output CFLAGS="-fPIC" ./configure --with-jasper=/usr/local/lib --disable-fortran --enable-python
  - ../.travis_no_output make
  - ../.travis_no_output sudo make install
  - cd python
  - ../../.travis_no_output sudo /usr/bin/python setup.py install
  - cd ../..

# distutils
  - ./.travis_no_output wget http://python-distribute.org/distribute_setup.py
  - ./.travis_no_output sudo /usr/bin/python distribute_setup.py

# cartopy
  - ./.travis_no_output git clone git://github.com/SciTools/cartopy.git
  - cd cartopy
  - ./.travis_no_output git checkout e68fae42093b6922d373e820e93584d917c4f882
  - ../.travis_no_output /usr/bin/python setup.py install --user
  - cd ..
  
# mo_unpack
  - wget https://puma.nerc.ac.uk/trac/UM_TOOLS/raw-attachment/wiki/unpack/unpack-030712.tgz
  - tar -xf unpack-030712.tgz
  - cd unpack-030712/libmo_unpack
#?  - gcc -c -fPIC -O4 -mfpmath=sse -msse -I include -D_LARGEFILE_SOURCE -D_LARGEFILE_SOURCE64 -D_FILE_OFFSET_BITS=64 *.c
  - gcc -c -fPIC -O4 -mfpmath=sse -msse -I include -D_LARGEFILE_SOURCE *.c
  - gcc -shared -Wl,-soname,libmo_unpack.so -o lib/libmo_unpack.so *.o
  - sudo cp lib/* /usr/local/lib
  - sudo cp include/* /usr/local/include
  - cd ../..

# iris
  - ./.travis_no_output /usr/bin/python setup.py --with-unpack build_ext --inplace -I/usr/local/include -L/usr/local/lib -R/usr/local/lib
  - ./.travis_no_output /usr/bin/python setup.py std_names
  - sudo mkdir /iris_test_data
  - echo -e "[Resources]\ndata_repository = /iris_test_data\n" > lib/iris/etc/site.cfg
  - ln -s lib/iris /home/travis/.local/lib/python2.7/site-packages/iris

  
script:
  - echo --- RUNNING TESTS *currently limited to nodata tests* ---
  - /usr/bin/python setup.py test -n

#  - echo --- RUNNING DOCTESTS ---
#  - cd /home/travis/builds/SciTools/iris/docs/iris
#  - make doctest

#  - echo --- RUNNING EXTESTS ---
#  - make extest

